README.rst, berserk/clients.py
Adds the remaining Board API endpoints:
- `/api/board/game/{game_id}/chat`
- `/api/board/game/{game_id}/claim-victory`
- `/api/board/game/{game_id}/berserk`
=> Add remaining Board API endpoints

README.rst, pyproject.toml
This should "fix" the double license entries in the pypi page
=> Use GPLv3+ trove classifier

berserk/clients.py
Updates `Games.export_multi`, `Studies.export_chapter`, and `Studies.export` to prepend `api/` to their paths. Interestingly enough, they worked as it was before but utilizing the path documented in the API will allow for the `check-endpoints` script to pick them up as implemented.
Related to #6
=> Update endpoint paths

README.rst, berserk/clients.py
Added REST endpoint for /api/bot/online.
This is to implement the first task in the issue https://github.com/lichess-org/berserk/issues/6. 
This is my first PR for this project. If this PR is ok, I plan to implement all the tasks under this issue.
All tests are getting passed when run locally.
=> added /api/bot/online API

CHANGELOG.rst, berserk/utils.py, tests/test_utils.py
Currently endpoints whose responses are converted with `models.Tournament.convert` are broken where the server returns date strings instead of milliseconds. The `TIME_FMT` mentioned here is not the one that is being returned by Lichess but rather standard ISO 8601 strings.
I found `tournaments.get_tournament`, `tournaments.create_arena`, & `tournaments.create_swiss` to be broken following a discord report. They seem to work with the changes here. I don't know why some of `client.challenges` functions need `models.Tournament.convert` but they still work following this change too.
=> Fix parsing time strings

check-endpoints.py
Fixes #10 
Issue was a result of how the regex search is being performed. It searches for each item without the leading '/', and it doesn't search in the context of the item being used as an exact path.
So "/oauth" becomes "oauth" - which exists as a string on its own elsewhere in clients.py. "/api/token" becomes "api/token", which has a child ("api/token/test") in clients.py, which is being counted as a match because the string "api/token" can be found in the string "api/token/test").
I fixed this (kinda hacky) by adding a " (double quote) to the end of the string the regex searches for, so the examples above will now search for oauth**"** and api/token/test**"** - which do not exist on their own as distinct **path = "<insert path>** items.
A better fix would be to search for the string …
=> check-endpoints.py: Updating regex to treat search items as distinct path.

README.rst
**Context**:
The function is implemented in [this file](https://github.com/lichess-org/berserk/blob/b5f94f74a94372be9910430bf3bcf5e5798dc290/berserk/clients.py#L659), while it's missing in the README.
**Change**:
Add the missing function in the README file.
**Tested**:
N/A
=> Add a missing function in the README

README.rst, berserk/clients.py
Adding methods for /api/broadcast functionality (addressing #6  ):
get_multi --> /api/broadcast
get_tournament_pgn --> /api/broadcast/{broadcastTournamentID}.pgn
get_round_gpn --> /api/broadcast/round/{broadcastRoundID}.pgn
=> Adding methods to access /api/broadcast functionality

berserk/clients.py
I came across https://stackoverflow.com/q/41136410 yesterday. It's seems to me that having `yield from` for streaming endpoints is more desirable.
Also includes another nitpick commit for removing `fmt=JSON`.
=> Use `yield from` for all generators of streaming endpoints

README.rst, berserk/clients/teams.py
Thank you for the project. This is my first time contributing.
Implemented the following endpoints:
1. get_join_request
2. accept_join_request
3. get_swiss_tournament
I had a couple of questions. 
1. The already existing `kick_member` function doesn't return anything. However, the [API](https://lichess.org/api#tag/Teams/operation/teamIdKickUserId) suggests that it returns a dictionary, confirming if the member has been kicked or not. I have returned a dictionary in `accept_join_request`, and would like to know if I should keep it and change the `kick_member` function or change the `accept_join_request`. 
2. In `get_join_request`, I am returning a iterator, I am unsure about the formatting type, so I left it as default. I have tested it, and it did work as intended but wanted to confirm if …
=> Implemented 3 API endpoints for Teams

README.rst, berserk/clients/teams.py
Implemented the Decline Join Request API endpoint. Addresses one bulletpoint in https://github.com/lichess-org/berserk/issues/6.
=> Implement Decline Join Request API

CHANGELOG.rst, README.rst, berserk/__init__.py, berserk/clients/users.py, berserk/types/__init__.py, berserk/types/common.py, berserk/types/team.py, tests/clients/cassettes/test_users/TestLichessGames.test_get_by_autocomplete.yaml, tests/clients/cassettes/test_users/TestLichessGames.test_get_by_autocomplete_as_object.yaml, tests/clients/cassettes/test_users/TestLichessGames.test_get_by_autocomplete_as_object_not_found.yaml, tests/clients/cassettes/test_users/TestLichessGames.test_get_by_autocomplete_not_found.yaml, tests/clients/test_users.py, tests/clients/utils.py
Implementing api/player/autocomplete api.
I got one questions regarding the param "friend", the name and definition of this parameter is unclear to me. 
Thus, I didn't add it to the implementation at this moment. Hope that somebody could explain to me.
The Documentation link: https://lichess.org/api#tag/Users/operation/apiPlayerAutocomplete
=> implement api/player/autocomplete

README.rst, berserk/clients/teams.py
Implement `message_all` = `/team/{teamId}/pm-all`
Please check off `/team/{teamId}/pm-all` in issue description for #6.
=> Implement `/team/{teamId}/pm-all` endpoint

CHANGELOG.rst, README.rst, berserk/__init__.py, berserk/clients/tournaments.py, berserk/models.py, berserk/types/__init__.py, berserk/types/tournament.py, berserk/types/tournaments.py, tests/clients/cassettes/test_tournaments/TestLichessGames.test_arenas_result.yaml, tests/clients/cassettes/test_tournaments/TestLichessGames.test_swiss_result.yaml, tests/clients/test_tournaments.py, tests/clients/utils.py
1. Add all the remaining swiss endpoints:
`get_swiss_tournament_info `= `/api/swiss/{swiss_id}`
`update_swiss` = `api/swiss/{tournamentId}/edit`
`join_swiss_tournament` = `/api/swiss/{id}/join`
`get_swiss_tournament_result` = `/api/swiss/{id}/results`
`schedule_next_round` = `/api/swiss/{id}/schedule-next-round`
`terminate_swiss_tournament` = `/api/swiss/{id}/terminate`
`withdraw_swiss_tournament` = `/api/swiss/{id}/withdraw`
2. Add missing return type for tournament
=> Implement api/swiss endpoints

CHANGELOG.rst, README.rst, berserk/clients/__init__.py, berserk/clients/external_engine.py, berserk/types/__init__.py, berserk/types/common.py
Implements the following:
- `get` = GET `/api/external-engine`
- `get_by_id` = `/api/external-engines/{id}`
- `create` = POST `/api/external-engine`
-  `update` = PUT `/api/external-engine`
- `delete` = DEL `/api/external-engine`
Note that this PR does NOT include any of the endpoints that use a different domain than `https://lichess.org`.
Please check off the above endpoints in the issue description for #6 🙏
=> Implement `/api/external_engine` endpoints

CHANGELOG.rst, README.rst, berserk/clients/opening_explorer.py, tests/clients/cassettes/test_opening_explorer/TestMasterGames.test_export.yaml, tests/clients/test_opening_explorer.py
Implement `get_otb_master_game` = `/master/pgn/{game_id}`. 
I did not add a return type for the function as there is no provided way to return `ndjson`/`json` in the response, but the response will be a PGN (text) due to the nature of the API endpoint.
Please check off `/master/pgn/{game_id}` in issue description of #6.
=> Implement `/master/pgn/{game_id}`

CHANGELOG.rst, README.rst, berserk/clients/tournaments.py
- Implement `/swiss/{id}.trf`
- I am not sure how to define a return type `TRF` (as it is not JSON formattable), so the endpoint's return type will be `str`.
- This is the reason I did not include a test as the API endpoint does not return JSON.
Check off `/swiss/{id}.trf` in #6.
<details>
</details>
=> Implement `/swiss/{id}.trf` endpoint

CHANGELOG.rst, README.rst, berserk/__init__.py, berserk/clients/studies.py, berserk/types/__init__.py, berserk/types/studies.py
Hi there,
Thanks for the project!   This small PR add the `study/ImportPGN` endpoint.
https://lichess.org/api#tag/Studies/operation/apiStudyImportPGN
Testing with:
```python
session = berserk.TokenSession(API_TOKEN)
client = berserk.Client(session=session)
resp = client.studies.import_pgn(
study_id=STUDY_ID,
chapter_name="test",
pgn=PGN,
orientation="white",
)
for chapter in resp:
print(chapter)
```
Returning the imported chapters.
```
{'id': 'oavP10Ig', 'name': 'test'}
```
<details>
</details>
=> Adding `import_pgn` endpoints

CHANGELOG.rst, berserk/models.py, berserk/utils.py, tests/test_models.py
=> Bwtime fix

CHANGELOG.rst, README.rst, berserk/__init__.py, berserk/clients/tv.py, berserk/types/__init__.py, berserk/types/common.py, berserk/types/tv.py
Implements the [/tv/{channel}/feed](https://lichess.org/api#tag/TV/operation/tvChannelFeed) endpoint and adds TypeDicts.
**NOTE:**
I attempted to add a test for this ([test_tv.py](https://gist.github.com/trevorbayless/1e25b3dcc4b86739880231f6142f2eaa)) but for some reason vcrpy hangs during `make test_record` when hitting the test (possibly because this is a stream endpoint?). In the linked test, I clipped the stream at the first two results as this endpoint is an infinite stream.
Interestingly enough, if you remove `@pytest.mark.vcr` the test passes, but we want this as a cassette. I was able to manually create a cassette for this ([TestTV.test_stream_bullet_tv.yaml](https://gist.github.com/trevorbayless/4c5714537b4e8be739c3d93bd99c1b3a)) which works, but would be problematic if the …
=> Implement `/tv/{channel}/feed` endpoint

.github/workflows/integration_test.yml
Fixes github action during dependency setup
```
$ python -m pip install --upgrade pip
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found
```
=> Update test container

CHANGELOG.rst, berserk/clients/broadcasts.py
=> Fix for ``client.broadcasts.push_pgn_update`` and ``client.broadcasts.update_round``.

README.rst
client.explorer is not a module, it's client.opening_explorer.
Fixing typos in the README
<details>
</details>
=> fix typos in README
